services:
  redis:
    image: redis:7
    container_name: boxd-redis
    networks:
      - boxd-net
  redis-slow:
    image: redis:7
    container_name: boxd-redis-slow
    networks:
      - boxd-net
  api-boxd:
    container_name: muse-api
    image: unedotamps/letterboxd-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./model/model.pkl:/app/model/model.pkl
    ports:
      - 5000:5000
    networks:
      - boxd-net

networks:
  boxd-net:
    driver: bridge
